version: '3.8'
services:
  web:
    build: .
    ports:
      - "8085:80"
    networks:
      - monitor
    labels:
      org.label-schema.group: "web"
    container_name: static-nginx
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - monitor
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - monitor
networks:
  monitor:
    driver: bridge
